linters:
  enable-all: true
  disable:
    - scopelint
    - interfacer
    - varcheck
    - golint
    - structcheck
    - exhaustivestruct
    - nosnakecase
    - maligned
    - ifshort
    - deadcode